# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anger', models.FloatField()),
                ('disgust', models.FloatField()),
                ('fear', models.FloatField()),
                ('sadness', models.FloatField()),
                ('happiness', models.FloatField()),
                ('surprise', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('singer', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=8)),
                ('genre', models.CharField(max_length=30)),
                ('lyric', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='emotionsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Song'),
        ),
    ]
