# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='author',
            new_name='writer',
        ),
    ]
