# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20161212_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='singer',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='song',
            name='writer',
            field=models.CharField(max_length=120),
        ),
    ]
