# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20161213_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=48),
            preserve_default=False,
        ),
    ]
