# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20161213_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='id',
        ),
        migrations.AlterField(
            model_name='song',
            name='singer',
            field=models.CharField(max_length=120, primary_key=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=48, primary_key=True, serialize=False),
        ),
    ]
